USE `MoviesTonight`;


INSERT INTO `MOVIES` (MTitle, Rating)
SELECT DISTINCT MTITLE, Rating FROM DATASHEET;

SELECT * FROM MOVIES;

ALTER TABLE ARTIST 
DROP MTitle;
ALTER TABLE ARTIST
ADD CName varchar(50) default NULL;
ALTER TABLE ARTIST 
DROP Rating;

INSERT INTO `ARTIST` (CName)
SELECT DISTINCT CName FROM DATASHEET;

INSERT INTO `THEATER` (TName, Location, Phone)
SELECT DISTINCT TName, Location, Phone FROM DATASHEET;

SELECT * FROM THEATER;

SELECT DISTINCT SHOWTIME, MOVIES.ID,THEATER.ID;
describe theater;

ALTER TABLE THEATER
MODIFY Phone varchar(20) default NULL;
describe theater;

